---
title: "9_model_comparison"
output: html_document
date: "2025-03-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(fda.usc)
library(fda)
library(glmnet)
```

```{r}
firsttrial <- readRDS("firsttrial_data.rds")
```


```{r}
#helper function
fit_multinom_model <- function(data, predictors, target) {
  formula_str <- paste(target, "~", paste(predictors, collapse = " + "))
  formula_obj <- as.formula(formula_str)
  model <- nnet::multinom(formula_obj, data = data)
  return(model)
}

fit_random_forest <- function(data, predictors, target, ntree = 500) {
  data[[target]] <- as.factor(data[[target]])
  formula_str <- paste(target, "~", paste(predictors, collapse = " + "))
  formula_obj <- as.formula(formula_str)
  rf_model <- randomForest(formula_obj, data = data, ntree = ntree, importance = TRUE)
  return(rf_model)
}

```


```{r}
#load fpca scores
bspline_scores <- readRDS("fpca_scores_bspline.rds")
fourier_scores <- readRDS("fpca_scores_fourier.rds")

```


```{r}
#train test split function
split_data <- function(data, target_col, p = 0.75) {
  set.seed(123)
  idx <- createDataPartition(data[[target_col]], p = p, list = FALSE)
  train <- data[idx, ]
  test  <- data[-idx, ]
  return(list(train = train, test = test))
}

```


```{r}
#model runner function
run_models <- function(data, label = "Unknown", target_var = "matching.condition") {
  # Split data
  split <- split_data(data, target_var)
  train <- split$train
  test  <- split$test
  
  # Get predictor names
  predictors <- grep("^FP[12]\\.", names(train), value = TRUE)
  
  # Multinomial model
  model_multinom <- fit_multinom_model(train, predictors, target_var)
  pred_multi <- predict(model_multinom, newdata = test)
  acc_multi <- mean(pred_multi == test[[target_var]])
  
  # Random Forest model
  model_rf <- fit_random_forest(train, predictors, target_var)
  pred_rf <- predict(model_rf, newdata = test)
  acc_rf <- mean(pred_rf == test[[target_var]])
  
  # Return accuracies
  tibble(
    Basis = label,
    Target = target_var,
    Model = c("Multinomial", "Random Forest"),
    Accuracy = c(acc_multi, acc_rf)
  )
}

```


```{r}
#run results
# Matching Condition Target
results_bspline_match <- run_models(bspline_scores, "B-spline", "matching.condition")
results_fourier_match <- run_models(fourier_scores, "Fourier", "matching.condition")

# Subject Identifier Target
results_bspline_subj <- run_models(bspline_scores, "B-spline", "subject.identifier")
results_fourier_subj <- run_models(fourier_scores, "Fourier", "subject.identifier")

# Combine all results
results_all <- bind_rows(
  results_bspline_match,
  results_fourier_match,
  results_bspline_subj,
  results_fourier_subj
)

```
```{r}
#plot results 
knitr::kable(results_all, digits = 3, caption = "Model Accuracy by Target and Basis Type")

```

